## Implementing binary decision trees
* Use Pandas to do some feature engineering.
* Transform categorical variables into binary variables.
* Write a function to compute the number of misclassified examples in an intermediate node.
* Write a function to find the best feature to split on.
* Build a binary decision tree from scratch.
* Make predictions using the decision tree.
* Evaluate the accuracy of the decision tree.
* Visualize the decision at the root node.

**Important Note**: In this assignment, we will focus on building decision trees where the data contain **only binary (0 or 1) features**. This allows us to avoid dealing with:
* Multiple intermediate nodes in a split
* The thresholding issues of real-valued features.

This assignment **may be challenging**, so brace yourself :)

In [1]:
# Import some libs

import pandas
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Load the lending club dataset
We will be using the same [LendingClub](https://www.lendingclub.com/) dataset as in the previous assignment.

In [2]:
loans_df = pandas.read_csv('data/lending-club-data.csv', low_memory=False)

Like the previous assignment, we reassign the labels to have +1 for a safe loan, and -1 for a risky (bad) loan.

In [3]:
# safe_loans =  1 => safe
# safe_loans = -1 => risky
loans_df['safe_loans'] = loans_df['bad_loans'].apply(lambda x : +1 if x==0 else -1)
loans_df.drop(columns=['bad_loans'])

             id  member_id  ...  last_major_derog_none  safe_loans
0       1077501    1296599  ...                      1           1
1       1077430    1314167  ...                      1          -1
2       1077175    1313524  ...                      1           1
3       1076863    1277178  ...                      1           1
4       1075269    1311441  ...                      1           1
...         ...        ...  ...                    ...         ...
122602  9856168   11708132  ...                      0          -1
122603  9795013   11647121  ...                      0           1
122604  9695736   11547808  ...                      0          -1
122605  9684700   11536848  ...                      1          -1
122606  9604874   11457002  ...                      1           1

[122607 rows x 68 columns]

Unlike the previous assignment where we used several features, in this assignment, we will just be using 4 categorical
features: 

1. grade of the loan 
2. the length of the loan term
3. the home ownership status: own, mortgage, rent
4. number of years of employment.

Since we are building a binary decision tree, we will have to convert these categorical features to a binary representation in a subsequent section using 1-hot encoding.

In [4]:
features = ['grade',              # grade of the loan
            'term',               # the term of the loan
            'home_ownership',     # home_ownership status: own, mortgage or rent
            'emp_length',         # number of years of employment
           ]
target = 'safe_loans'
loans_df = loans_df[features + [target]]

Let's explore what the dataset looks like.

In [5]:
loans_df

       grade        term home_ownership emp_length  safe_loans
0          B   36 months           RENT  10+ years           1
1          C   60 months           RENT   < 1 year          -1
2          C   36 months           RENT  10+ years           1
3          C   36 months           RENT  10+ years           1
4          A   36 months           RENT    3 years           1
...      ...         ...            ...        ...         ...
122602     E   60 months       MORTGAGE        NaN          -1
122603     D   36 months       MORTGAGE  10+ years           1
122604     D   60 months       MORTGAGE    5 years          -1
122605     D   60 months       MORTGAGE  10+ years          -1
122606     A   36 months            OWN    3 years           1

[122607 rows x 5 columns]

In [74]:
print(sum(1 for x in loans_df[target].values if x==-1))

23150

## Subsample dataset to make sure classes are balanced
Just as we did in the previous assignment, we will undersample the larger class (safe loans) in order to balance out our dataset. This means we are throwing away many data points. We use `seed=1` so everyone gets the same results.

In [6]:
safe_loans_raw = loans_df[loans_df[target] == +1]
risky_loans_raw = loans_df[loans_df[target] == -1]

# Since there are fewer risky loans than safe loans, find the ratio of the sizes
# and use that percentage to undersample the safe loans.
percentage = risky_loans_raw.shape[0]/safe_loans_raw.shape[0]

risky_loans = risky_loans_raw
safe_loans = safe_loans_raw.sample(frac=percentage, random_state=1)

# Append the risky_loans with the downsampled version of safe_loans
loans_data = risky_loans.append(safe_loans)

print ("Percentage of safe loans                 : {}".format(safe_loans.shape[0] / loans_data.shape[0]))
print ("Percentage of risky loans                : {}".format(risky_loans.shape[0] / loans_data.shape[0]))
print ("Total number of loans in our new dataset : {}".format(loans_data.shape[0]))

Percentage of safe loans                 : 0.5
Percentage of risky loans                : 0.5
Total number of loans in our new dataset : 46300

**Note:** There are many approaches for dealing with imbalanced data, including some where we modify the learning algorithm. These approaches are beyond the scope of this course, but some of them are reviewed in "[Learning from Imbalanced Data](http://www.ele.uri.edu/faculty/he/PDFfiles/ImbalancedLearning.pdf)" by Haibo He and Edwardo A. Garcia, *IEEE Transactions on Knowledge and Data Engineering* **21**(9) (June 26, 2009), p. 1263–1284. For this assignment, we use the simplest possible approach, where we subsample the overly represented class to get a more balanced dataset. In general, and especially when the data is highly imbalanced, we recommend using more advanced methods.

## Transform categorical data into binary features
In this assignment, we will implement **binary decision trees** (decision trees for binary features, a specific case of categorical variables taking on two values, e.g., true/false). Since all of our features are currently categorical features, we want to turn them into binary features. 

For instance, the **home_ownership** feature represents the home ownership status of the loanee, which is either `own`, `mortgage` or `rent`. For example, if a data point has the feature 
```
   {'home_ownership': 'RENT'}
```
we want to turn this into three features: 
```
 { 
   'home_ownership = OWN'      : 0, 
   'home_ownership = MORTGAGE' : 0, 
   'home_ownership = RENT'     : 1
 }
```

In [7]:
print(loans_data.dtypes)
categorical_variables = list(loans_data.select_dtypes(include=['object']).columns)
print(categorical_variables)

one_hot_data = pandas.get_dummies(loans_data[categorical_variables], prefix=categorical_variables)
# need to add inplace in oreder to drop columns.
loans_data.drop(columns=categorical_variables, axis=1, inplace=True)
loans_data = pandas.concat([loans_data, one_hot_data], axis=1)

print(loans_data['grade_A'].values.sum())

grade             object
term              object
home_ownership    object
emp_length        object
safe_loans         int64
dtype: object
['grade', 'term', 'home_ownership', 'emp_length']
6508

## Train-test split

We split the data into a train test split with 80% of the data in the training set and 20% of the data in the test set. We use `seed=1` so that everyone gets the same result.

In [8]:
np.random.seed(1)

train_data, test_data = train_test_split(loans_data, test_size=0.2)

# Decision tree implementation
In this section, we will implement binary decision trees from scratch. There are several steps involved in building a decision tree. For that reason, we have split the entire assignment into several sections.

## Function to count number of mistakes while predicting majority class

Recall from the lecture that prediction at an intermediate node works by predicting the **majority class** for all data points that belong to this node.

Now, we will write a function that calculates the number of **missclassified examples** when predicting the **majority class**. This will be used to help determine which feature is the best to split on at a given node of the tree.

**Note**: Keep in mind that in order to compute the number of mistakes for a majority classifier, we only need the label (y values) of the data points in the node. 

** Steps to follow **:
* ** Step 1:** Calculate the number of safe loans and risky loans.
* ** Step 2:** Since we are assuming majority class prediction, all the data points that are **not** in the majority class are considered **mistakes**.
* ** Step 3:** Return the number of **mistakes**.


Now, let us write the function `intermediate_node_num_mistakes` which computes the number of misclassified examples of an intermediate node given the set of labels (y values) of the data points contained in the node. Fill in the places where you find `## YOUR CODE HERE`. There are **three** places in this function for you to fill in.

In [9]:
def intermediate_node_num_mistakes(labels_in_node):
    # Corner case: If labels_in_node is empty, return 0
    if len(labels_in_node) == 0:
        return 0
    
    # Count the number of 1's (safe loans)
    safe_loans_count = sum(labels_in_node==1)
    
    # Count the number of -1's (risky loans)
    risky_loans_count = sum(labels_in_node==-1)
                
    # Return the number of mistakes that the majority classifier makes.
    return min(safe_loans_count, risky_loans_count)

Because there are several steps in this assignment, we have introduced some stopping points where you can check your code and make sure it is correct before proceeding. To test your `intermediate_node_num_mistakes` function, run the following code until you get a **Test passed!**, then you should proceed. Otherwise, you should spend some time figuring out where things went wrong.

In [10]:
# Test case 1
example_labels = np.array([-1, -1, 1, 1, 1])
if intermediate_node_num_mistakes(example_labels) == 2:
    print ('Test passed!')
else:
    print ('Test 1 failed... try again!')

# Test case 2
example_labels = np.array([-1, -1, 1, 1, 1, 1, 1])
if intermediate_node_num_mistakes(example_labels) == 2:
    print ('Test passed!')
else:
    print ('Test 2 failed... try again!')
    
# Test case 3
example_labels = np.array([-1, -1, -1, -1, -1, 1, 1])
if intermediate_node_num_mistakes(example_labels) == 2:
    print ('Test passed!')
else:
    print ('Test 3 failed... try again!')

Test passed!
Test passed!
Test passed!

## Function to pick best feature to split on
The function **best_splitting_feature** takes 3 arguments: 
1. The data (DataFrame of data which includes all of the feature columns and label column)
2. The features to consider for splits (a list of strings of column names to consider for splits)
3. The name of the target/label column (string)

The function will loop through the list of possible features, and consider splitting on each of them. It will calculate the classification error of each split and return the feature that had the smallest classification error when split on.

Recall that the **classification error** is defined as follows:
$$
\mbox{classification error} = \frac{\mbox{# mistakes}}{\mbox{# total examples}}
$$

Follow these steps: 
* **Step 1:** Loop over each feature in the feature list
* **Step 2:** Within the loop, split the data into two groups: one group where all of the data has feature value 0 or False (we will call this the **left** split), and one group where all of the data has feature value 1 or True (we will call this the **right** split). Make sure the **left** split corresponds with 0 and the **right** split corresponds with 1 to ensure your implementation fits with our implementation of the tree building process.
* **Step 3:** Calculate the number of misclassified examples in both groups of data and use the above formula to compute the **classification error**.
* **Step 4:** If the computed error is smaller than the best error found so far, store this **feature and its error**.

This may seem like a lot, but we have provided pseudocode in the comments in order to help you implement the function correctly.

**Note:** Remember that since we are only dealing with binary features, we do not have to consider thresholds for real-valued features. This makes the implementation of this function much easier.

Fill in the places where you find `## YOUR CODE HERE`. There are **five** places in this function for you to fill in.

In [17]:
def best_splitting_feature(data, features, target):
    
    best_feature = None # Keep track of the best feature 
    best_error = 10     # Keep track of the best error so far 
    # Note: Since error is always <= 1, we should intialize it with something larger than 1.

    # Convert to float to make sure error gets computed correctly.
    num_data_points = float(len(data))  
    
    # Loop through each feature to consider splitting on that feature
    for feature in features:
        
        # The left split will have all data points where the feature value is 0
        left_split = data[data[feature] == 0]
        
        # The right split will have all data points where the feature value is 1
        right_split = data[data[feature] == 1]
            
        # Calculate the number of misclassified examples in the left split.
        # Remember that we implemented a function for this! (It was called intermediate_node_num_mistakes)
        left_mistakes = intermediate_node_num_mistakes(left_split[target])

        # Calculate the number of misclassified examples in the right split.
        right_mistakes = intermediate_node_num_mistakes(right_split[target])
            
        # Compute the classification error of this split.
        # Error = (# of mistakes (left) + # of mistakes (right)) / (# of data points)
        error = (left_mistakes + right_mistakes) / data.shape[0]

        # If this is the best error we have found so far, store the feature as best_feature and the error as best_error
        if error < best_error:
            best_error = error
            best_feature = feature
    
    return best_feature # Return the best feature we found

To test your `best_splitting_feature` function, run the following code:

In [19]:
features = list(loans_data.columns)
features.remove('safe_loans')

if best_splitting_feature(train_data, features, 'safe_loans') == 'term_ 36 months':
    print ('Test passed!')
else:
    print ('Test failed... try again!')

Test passed!

## Building the tree

With the above functions implemented correctly, we are now ready to build our decision tree. Each node in the decision tree is represented as a dictionary which contains the following keys and possible values:

    { 
       'is_leaf'            : True/False.
       'prediction'         : Prediction at the leaf node.
       'left'               : (dictionary corresponding to the left tree).
       'right'              : (dictionary corresponding to the right tree).
       'splitting_feature'  : The feature that this node splits on.
    }

First, we will write a function that creates a leaf node given a set of target values. Fill in the places where you find `## YOUR CODE HERE`. There are **three** places in this function for you to fill in.

In [64]:
def create_leaf(target_values):
    
    # Create a leaf node
    leaf = {'splitting_feature' : None,
            'left' : None,
            'right' : None,
            'is_leaf': True}  
    
    # Count the number of data points that are +1 and -1 in this node.
    num_ones = target_values[target_values == +1].shape[0]
    num_minus_ones = target_values[target_values == -1].shape[0]
    
    # For the leaf node, set the prediction to be the majority class.
    # Store the predicted class (1 or -1) in leaf['prediction']
    if num_ones > num_minus_ones:
        leaf['prediction'] = 1
    else:
        leaf['prediction'] = -1
        

        
    # Return the leaf node        
    return leaf

We have provided a function that learns the decision tree recursively and implements 3 stopping conditions:
1. **Stopping condition 1:** All data points in a node are from the same class.
2. **Stopping condition 2:** No more features to split on.
3. **Additional stopping condition:** In addition to the above two stopping conditions covered in lecture, in this assignment we will also consider a stopping condition based on the **max_depth** of the tree. By not letting the tree grow too deep, we will save computational effort in the learning process. 

Now, we will write down the skeleton of the learning algorithm. Fill in the places where you find `## YOUR CODE HERE`. There are **seven** places in this function for you to fill in.

In [66]:
def decision_tree_create(data, features, target, current_depth = 0, max_depth = 10):
    remaining_features = features[:] # Make a copy of the features.
    
    target_values = data[target]
    print ("--------------------------------------------------------------------")
    print ("Subtree, depth = %s (%s data points)." % (current_depth, target_values.shape[0]))
    

    # Stopping condition 1
    # (Check if there are mistakes at current node.
    # Recall you wrote a function intermediate_node_num_mistakes to compute this.)
    if intermediate_node_num_mistakes(target_values)==0:
        print ("Stopping condition 1 reached.")     
        # If not mistakes at current node, make current node a leaf node
        return create_leaf(target_values)
    
    # Stopping condition 2 (check if there are remaining features to consider splitting on)
    if len(remaining_features)==0:  
        print ("Stopping condition 2 reached.")    
        # If there are no remaining features to consider, make current node a leaf node
        return create_leaf(target_values)    
    
    # Additional stopping condition (limit tree depth)
    if current_depth>=max_depth:
        print ("Reached maximum depth. Stopping for now.")
        # If the max tree depth has been reached, make current node a leaf node
        return create_leaf(target_values)

    # Find the best splitting feature (recall the function best_splitting_feature implemented above)
    ## YOUR CODE HERE
    splitting_feature = best_splitting_feature(data, remaining_features, target)
    
    # Split on the best feature that we found. 
    left_split = data[data[splitting_feature] == 0]
    right_split = data[data[splitting_feature] == 1]
    remaining_features.remove(splitting_feature)
    print ("Split on feature %s. (%s, %s)" % (\
                      splitting_feature, len(left_split), len(right_split)))
    
    # Create a leaf node if the split is "perfect"
    if left_split.shape[0] == data.shape[0]:
        print ("Creating leaf node.")
        return create_leaf(left_split[target])
         
    if right_split.shape[0] == data.shape[0]:
        print ("Creating leaf node.")
        return create_leaf(right_split[target])
         
        
    # Repeat (recurse) on left and right subtrees
    left_tree = decision_tree_create(left_split, remaining_features, target, current_depth + 1, max_depth)        
    right_tree = decision_tree_create(right_split, remaining_features, target, current_depth + 1, max_depth)

    return {'is_leaf'          : False, 
            'prediction'       : None,
            'splitting_feature': splitting_feature,
            'left'             : left_tree, 
            'right'            : right_tree}

Here is a recursive function to count the nodes in your tree:

In [67]:
def count_nodes(tree):
    if tree['is_leaf']:
        return 1
    return 1 + count_nodes(tree['left']) + count_nodes(tree['right'])

Run the following test code to check your implementation. Make sure you get **'Test passed'** before proceeding.

In [68]:
small_data_decision_tree = decision_tree_create(train_data, features, 'safe_loans', max_depth = 3)
if count_nodes(small_data_decision_tree) == 13:
    print ('Test passed!')
else:
    print ('Test failed... try again!')
    print ('Number of nodes found                :', count_nodes(small_data_decision_tree))
    print ('Number of nodes that should be there : 13')

--------------------------------------------------------------------
Subtree, depth = 0 (37040 data points).
Split on feature term_ 36 months. (9419, 27621)
--------------------------------------------------------------------
Subtree, depth = 1 (9419 data points).
Split on feature grade_A. (9293, 126)
--------------------------------------------------------------------
Subtree, depth = 2 (9293 data points).
Split on feature grade_B. (8227, 1066)
--------------------------------------------------------------------
Subtree, depth = 3 (8227 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 3 (1066 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 2 (126 data points).
Split on feature home_ownership_MORTGAGE. (36, 90)
--------------------------------------------------------------------
Subtree, depth = 3 (36 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 3 (90 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 1 (27621 data points).
Split on feature grade_D. (22974, 4647)
--------------------------------------------------------------------
Subtree, depth = 2 (22974 data points).
Split on feature grade_E. (21728, 1246)
--------------------------------------------------------------------
Subtree, depth = 3 (21728 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 3 (1246 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 2 (4647 data points).
Split on feature grade_A. (4647, 0)
Creating leaf node.
Test passed!

## Build the tree!

Now that all the tests are passing, we will train a tree model on the **train_data**. Limit the depth to 6 (**max_depth = 6**) to make sure the algorithm doesn't run for too long. Call this tree **my_decision_tree**. 

**Warning**: This code block may take 1-2 minutes to learn.

In [69]:
# YOUR CODE HERE
my_decision_tree = decision_tree_create(train_data, features, 'safe_loans', max_depth =6)

--------------------------------------------------------------------
Subtree, depth = 0 (37040 data points).
Split on feature term_ 36 months. (9419, 27621)
--------------------------------------------------------------------
Subtree, depth = 1 (9419 data points).
Split on feature grade_A. (9293, 126)
--------------------------------------------------------------------
Subtree, depth = 2 (9293 data points).
Split on feature grade_B. (8227, 1066)
--------------------------------------------------------------------
Subtree, depth = 3 (8227 data points).
Split on feature grade_C. (5974, 2253)
--------------------------------------------------------------------
Subtree, depth = 4 (5974 data points).
Split on feature grade_D. (3891, 2083)
--------------------------------------------------------------------
Subtree, depth = 5 (3891 data points).
Split on feature grade_E. (1721, 2170)
--------------------------------------------------------------------
Subtree, depth = 6 (1721 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (2170 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 5 (2083 data points).
Split on feature grade_E. (2083, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 4 (2253 data points).
Split on feature grade_D. (2253, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 3 (1066 data points).
Split on feature emp_length_5 years. (986, 80)
--------------------------------------------------------------------
Subtree, depth = 4 (986 data points).
Split on feature emp_length_3 years. (900, 86)
--------------------------------------------------------------------
Subtree, depth = 5 (900 data points).
Split on feature grade_C. (900, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 5 (86 data points).
Split on feature home_ownership_MORTGAGE. (39, 47)
--------------------------------------------------------------------
Subtree, depth = 6 (39 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (47 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 4 (80 data points).
Split on feature home_ownership_RENT. (58, 22)
--------------------------------------------------------------------
Subtree, depth = 5 (58 data points).
Split on feature grade_C. (58, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 5 (22 data points).
Split on feature grade_C. (22, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 2 (126 data points).
Split on feature home_ownership_MORTGAGE. (36, 90)
--------------------------------------------------------------------
Subtree, depth = 3 (36 data points).
Split on feature emp_length_< 1 year. (26, 10)
--------------------------------------------------------------------
Subtree, depth = 4 (26 data points).
Split on feature emp_length_2 years. (23, 3)
--------------------------------------------------------------------
Subtree, depth = 5 (23 data points).
Split on feature emp_length_5 years. (20, 3)
--------------------------------------------------------------------
Subtree, depth = 6 (20 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (3 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 5 (3 data points).
Split on feature grade_B. (3, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 4 (10 data points).
Split on feature grade_B. (10, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 3 (90 data points).
Split on feature grade_B. (90, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 1 (27621 data points).
Split on feature grade_D. (22974, 4647)
--------------------------------------------------------------------
Subtree, depth = 2 (22974 data points).
Split on feature grade_E. (21728, 1246)
--------------------------------------------------------------------
Subtree, depth = 3 (21728 data points).
Split on feature grade_C. (14570, 7158)
--------------------------------------------------------------------
Subtree, depth = 4 (14570 data points).
Split on feature grade_F. (14207, 363)
--------------------------------------------------------------------
Subtree, depth = 5 (14207 data points).
Split on feature grade_G. (14097, 110)
--------------------------------------------------------------------
Subtree, depth = 6 (14097 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (110 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 5 (363 data points).
Split on feature grade_A. (363, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 4 (7158 data points).
Split on feature home_ownership_RENT. (3458, 3700)
--------------------------------------------------------------------
Subtree, depth = 5 (3458 data points).
Split on feature emp_length_< 1 year. (3257, 201)
--------------------------------------------------------------------
Subtree, depth = 6 (3257 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (201 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 5 (3700 data points).
Split on feature emp_length_2 years. (3279, 421)
--------------------------------------------------------------------
Subtree, depth = 6 (3279 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 6 (421 data points).
Reached maximum depth. Stopping for now.
--------------------------------------------------------------------
Subtree, depth = 3 (1246 data points).
Split on feature grade_A. (1246, 0)
Creating leaf node.
--------------------------------------------------------------------
Subtree, depth = 2 (4647 data points).
Split on feature grade_A. (4647, 0)
Creating leaf node.

## Making predictions with a decision tree

As discussed in the lecture, we can make predictions from the decision tree with a simple recursive function. Below, we call this function `classify`, which takes in a learned `tree` and a test point `x` to classify.  We include an option `annotate` that describes the prediction path when set to `True`.

Fill in the places where you find `## YOUR CODE HERE`. There is **one** place in this function for you to fill in.

In [75]:
def classify(tree, x, annotate = False):   
    # if the node is a leaf node.
    if tree['is_leaf']:
        if annotate: 
            print ("At leaf, predicting %s" % tree['prediction'])
        return tree['prediction'] 
    else:
        # split on feature.
        split_feature_value = x[tree['splitting_feature']]
        if annotate: 
            print ("Split on %s = %s" % (tree['splitting_feature'], split_feature_value))
        if split_feature_value == 0:
            return classify(tree['left'], x, annotate)
        else:
            return classify(tree['right'], x, annotate) ### YOUR CODE HERE

Now, let's consider the first example of the test set and see what `my_decision_tree` model predicts for this data point.

In [71]:
test_data.iloc[0]

safe_loans                -1
grade_A                    0
grade_B                    0
grade_C                    0
grade_D                    0
grade_E                    1
grade_F                    0
grade_G                    0
term_ 36 months            1
term_ 60 months            0
home_ownership_MORTGAGE    0
home_ownership_OTHER       0
home_ownership_OWN         0
home_ownership_RENT        1
emp_length_1 year          0
emp_length_10+ years       1
emp_length_2 years         0
emp_length_3 years         0
emp_length_4 years         0
emp_length_5 years         0
emp_length_6 years         0
emp_length_7 years         0
emp_length_8 years         0
emp_length_9 years         0
emp_length_< 1 year        0
Name: 121355, dtype: int64

In [72]:
print ('Predicted class: %s ' % classify(my_decision_tree, test_data.iloc[0]))

Predicted class: -1

Let's add some annotations to our prediction to see what the prediction path was that lead to this predicted class:

In [73]:
classify(my_decision_tree, test_data.iloc[0], annotate=True)

Split on term_ 36 months = 1
Split on grade_D = 0
Split on grade_E = 1
At leaf, predicting -1

-1

**Quiz Question:** What was the feature that **my_decision_tree** first split on while making the prediction for test_data[0]?
<br>
**Your answer:** 
<br>
**Quiz Question:** What was the first feature that lead to a right split of test_data[0]?
<br>
**Your answer:**
<br>
**Quiz Question:** What was the last feature split on before reaching a leaf node for test_data[0]?
<br>
**Your answer:**

## Evaluating your decision tree
Now, we will write a function to evaluate a decision tree by computing the classification error of the tree on the given dataset.

Again, recall that the **classification error** is defined as follows:
$$
\mbox{classification error} = \frac{\mbox{# mistakes}}{\mbox{# total examples}}
$$

Now, write a function called `evaluate_classification_error` that takes in as input:
1. `tree` (as described above)
2. `data` (an DataFrame)
3. `target` (a string - the name of the target/label column)

This function should calculate a prediction (class label) for each row in `data` using the decision `tree` and return the classification error computed using the above formula. Fill in the places where you find `## YOUR CODE HERE`. There is **one** place in this function for you to fill in.

In [90]:
print (test_data.shape[0])
def evaluate_classification_error(tree, data, target):
    # Apply the classify(tree, x) to each row in your data
    prediction = []
    for i, row in data.iterrows():
        prediction.append(classify(tree, row))
    
    # Once you've made the predictions, calculate the classification error and return it
    ## YOUR CODE HERE
    return sum(data[target]!=prediction)/len(data)

9260

Now, let's use this function to evaluate the classification error on the test set.

In [91]:
evaluate_classification_error(my_decision_tree, test_data, 'safe_loans')

0.3827213822894168

**Quiz Question:** Rounded to 2nd decimal point, what is the classification error of **my_decision_tree** on the **test_data**?
<br>
**Your answer:** 0.38